apiVersion: v1
kind: ConfigMap
metadata:
    namespace: development
    name: website-configmap
data:
    database_url: postgres://django_wow:django_wow@postgresql-dynamic-service:5432/django_wow
    broker_url: amqp://rabbitmq-deploy-service:5672
    result_url: redis://redis-deploy-service:6379
---
apiVersion: v1
kind: ConfigMap
metadata:
    namespace: development
    name: mail-configmap
data:
    database_host: postgresql-dynamic-service:5432

