apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deploy
  namespace: development
  labels:
    app: postgresql-deploy
    restartPolicy: Always
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-deploy
  template:
    metadata:
      labels:
        app: postgresql-deploy
    spec:
      containers:
        - name: postgresql-deploy
          image: wow_postgres
          imagePullPolicy: Never
          ports:
          - containerPort: 5432
          volumeMounts:
          - name: postgres-persistent-storage
            mountPath: /var/lib/postgresql/data
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: postgres-root-password
          - name: DJANGO_DB_USER
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: django-db-user
          - name: DJANGO_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: django-db-pass
          - name: DJANGO_DB_NAME
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: django-db-name
          - name: MAIL_DB_USER
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: mail-db-user
          - name: MAIL_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: mail-db-pass
          - name: MAIL_DB_NAME
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: mail-db-name
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgresql-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-dynamic-service
  namespace: development
spec:
  type: NodePort
  selector:
    app: postgresql-deploy
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432
