---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: postgres-pv-volume
    labels:
        type: local

spec:
    capacity:
        storage: 5Gi
    accessModes:
    - ReadWriteMany
    hostPath:
        path: "/mnt/data/kubernetes/postgresql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    namespace: development
    name: postgresql-claim
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 5Gi
