# Generated by Django 4.0.2 on 2022-04-07 15:38

import apps.core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('next', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_board', to='forums.board')),
                ('prev', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='previous_board', to='forums.board')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forums.board')),
                ('next', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_forum', to='forums.forum')),
                ('prev', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='previous_forum', to='forums.forum')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('text', models.CharField(blank=True, max_length=30, verbose_name='Display Text')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=apps.core.models.user_directory_path)),
                ('fg_color', models.CharField(default='FFFFFF', max_length=6)),
                ('bg_color', models.CharField(default='000000', max_length=6)),
                ('corner_radius', models.PositiveSmallIntegerField(default=0)),
                ('stroke_width', models.PositiveSmallIntegerField(default=5)),
                ('fill', models.BooleanField(default=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forums.board')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('comment', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forums.forum')),
                ('replies', models.ManyToManyField(to='forums.Post')),
            ],
        ),
    ]
