#!/bin/sh
#
# postfix      Postfix Mail Transfer Agent
#
# chkconfig: - 80 30
# description: Postfix is a Mail Transport Agent, which is the program \
#              that moves mail from one machine to another.
# processname: master
# pidfile: /var/spool/postfix/pid/master.pid
# config: /etc/postfix/main.cf
# config: /etc/postfix/master.cf
#
# Based on startup script from Simon J Mudd <sjmudd@pobox.com>

### BEGIN INIT INFO
# Provides: postfix MTA
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Short-Description: start and stop postfix
# Description: Postfix is a Mail Transport Agent, which is the program that 
#              moves mail from one machine to another.
### END INIT INFO

RETVAL=0
running=0
prog="postfix"
if [ -f /var/spool/postfix/pid/master.pid ]; then
  running=`cat /var/spool/postfix/pid/master.pid`
fi


conf_check() {
    [ -x /usr/sbin/postfix ] || exit 5
    [ -d /etc/postfix ] || exit 6
    [ -d /var/mail/domains ] || exit 5
}

start() {
        conf_check
        # Start daemons.
        echo -n "Starting postfix: "
        /usr/bin/newaliases >/dev/null 2>&1
        /usr/sbin/postfix start 2>/dev/null 1>&2
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/postfix
        echo
        return $RETVAL
}

stop() {
        conf_check
        # Stop daemons.
        echo -n "Shutting down postfix: "
        /usr/sbin/postfix stop 2>/dev/null 1>&2
        RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/postfix
        echo
        return $RETVAL
}

reload() {
        conf_check
        echo -n "Reloading postfix: "
        /usr/sbin/postfix reload 2>/dev/null 1>&2
        RETVAL=$?
        echo
        return $RETVAL
}

abort() {
        conf_check
        /usr/sbin/postfix abort 2>/dev/null 1>&2
        return $?
}

flush() {
        conf_check
        /usr/sbin/postfix flush 2>/dev/null 1>&2
        return $?
}

check() {
        conf_check
        /usr/sbin/postfix check 2>/dev/null 1>&2
        return $?
}

# See how we were called.
case "$1" in
  start)
        [ $running -eq 0 ] || exit 0
        start
        ;;
  stop)
        [ $running -gt 0 ] || exit 0
        stop
        ;;
  restart|force-reload)
        stop
        start
        ;;
  reload)
        [ $running -gt 0 ] || exit 7
        reload
        ;;
  abort)
        abort
        ;;
  flush)
        flush
        ;;
  check)
        check
        ;;
  status)
        status master
        ;;
  condrestart)
        [ $running -eq 0 ] || exit 0
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|abort|flush|check|status|condrestart}"
         exit 2
esac

exit $?
