# Generated by Django 4.0.2 on 2022-04-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.URLField()),
                ('inset', models.URLField()),
                ('main', models.URLField()),
                ('raw', models.URLField()),
                ('character_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField()),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('main_character', models.BooleanField(default=False, verbose_name='Main Character')),
            ],
        ),
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Masculine Name')),
                ('female', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Feminine Name')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Generic Name')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectedRealm',
            fields=[
                ('connected_realm_id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FactionName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20)),
                ('gender_id', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GenderName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuildRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_rank', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayableClass',
            fields=[
                ('slug', models.SlugField()),
                ('class_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/class')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Playable Classes',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('slug', models.SlugField()),
                ('race_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Masculine Name')),
                ('female', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Feminine Name')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Generic Name')),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('slug', models.SlugField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('realm_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('timezone', models.CharField(max_length=50)),
                ('is_tournament_realm', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RealmName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealmType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RealmTypeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('slug', models.SlugField()),
                ('spec_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/spec')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Playable Specialization',
            },
        ),
        migrations.CreateModel(
            name='SpecName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('male', models.TextField(blank=True, default='', max_length=50, null=True, verbose_name='Male description')),
                ('female', models.TextField(blank=True, default='', max_length=50, null=True, verbose_name='Female description')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=25, verbose_name='Stat Slug')),
            ],
        ),
        migrations.CreateModel(
            name='StatName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
