# Generated by Django 4.0.2 on 2022-04-07 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statname',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.locale'),
        ),
        migrations.AddField(
            model_name='statname',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.stat'),
        ),
        migrations.AddField(
            model_name='specname',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.locale'),
        ),
        migrations.AddField(
            model_name='specname',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.spec'),
        ),
        migrations.AddField(
            model_name='spec',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.playableclass', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='realmtypename',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.locale'),
        ),
        migrations.AddField(
            model_name='realmtypename',
            name='realm_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.realmtype'),
        ),
        migrations.AddField(
            model_name='realmname',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.locale'),
        ),
        migrations.AddField(
            model_name='realmname',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.realm'),
        ),
        migrations.AddField(
            model_name='realm',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.region'),
        ),
        migrations.AddField(
            model_name='realm',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.realmtype'),
        ),
        migrations.AddField(
            model_name='racename',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.locale'),
        ),
        migrations.AddField(
            model_name='racename',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.race'),
        ),
        migrations.AddField(
            model_name='race',
            name='allowed_classes',
            field=models.ManyToManyField(blank=True, to='core.PlayableClass'),
        ),
        migrations.AddField(
            model_name='race',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.faction'),
        ),
        migrations.AddField(
            model_name='guildrank',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.guild'),
        ),
        migrations.AddField(
            model_name='guild',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.faction'),
        ),
        migrations.AddField(
            model_name='guild',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.realm'),
        ),
        migrations.AddField(
            model_name='guild',
            name='roster',
            field=models.ManyToManyField(blank=True, to='core.Character'),
        ),
        migrations.AddField(
            model_name='gendername',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.gender'),
        ),
        migrations.AddField(
            model_name='gendername',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.locale'),
        ),
        migrations.AddField(
            model_name='factionname',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.faction'),
        ),
        migrations.AddField(
            model_name='factionname',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.locale'),
        ),
        migrations.AddField(
            model_name='connectedrealm',
            name='connected_realms',
            field=models.ManyToManyField(to='core.Realm'),
        ),
        migrations.AddField(
            model_name='classname',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.playableclass', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='classname',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.locale'),
        ),
        migrations.AddField(
            model_name='character',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.account', verbose_name='Blizzard Account'),
        ),
        migrations.AddField(
            model_name='character',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.playableclass', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='character',
            name='current_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.spec'),
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.gender'),
        ),
        migrations.AddField(
            model_name='character',
            name='guild_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.guildrank'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.race'),
        ),
        migrations.AddField(
            model_name='character',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.realm'),
        ),
        migrations.AlterUniqueTogether(
            name='specname',
            unique_together={('locale', 'spec')},
        ),
        migrations.AlterUniqueTogether(
            name='realmname',
            unique_together={('locale', 'realm')},
        ),
        migrations.AlterUniqueTogether(
            name='realm',
            unique_together={('realm_id', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='racename',
            unique_together={('locale', 'race')},
        ),
        migrations.AlterUniqueTogether(
            name='gendername',
            unique_together={('gender', 'locale')},
        ),
        migrations.AlterUniqueTogether(
            name='classname',
            unique_together={('locale', 'cls')},
        ),
    ]
