# Generated by Django 4.0.2 on 2022-04-09 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_account_user_alter_user_region'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account', verbose_name='Blizzard Account'),
        ),
    ]
