# Generated by Django 4.0.2 on 2022-04-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_character_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='playableclass',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spec',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
