# Generated by Django 4.0.2 on 2022-04-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_playableclass_icon_url_spec_icon_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playableclass',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='spec',
            name='icon',
        ),
    ]
