# Generated by Django 4.0.2 on 2022-04-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_playableclass_icon_remove_spec_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playableclass',
            old_name='icon_url',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='spec',
            old_name='icon_url',
            new_name='icon',
        ),
    ]
