# Generated by Django 4.0.2 on 2022-04-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_icon_playableclass_icon_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playableclass',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='spec',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
