# Generated by Django 4.0.2 on 2022-04-17 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_playableclass_icon_alter_spec_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playableclass',
            name='icon_url',
        ),
    ]
