# Generated by Django 4.0.2 on 2022-04-18 01:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_spec_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playableclass',
            name='icon',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='icons/class', location='/home/david/Projects/battlenet/django_wow/src/django_wow/static/icons/class/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='spec',
            name='icon',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='icons/spec', location='/home/david/Projects/battlenet/django_wow/src/django_wow/static/icons/spec/'), upload_to=''),
        ),
    ]
