# Generated by Django 4.0.2 on 2022-04-18 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_locale_is_active_region_is_active'),
        ('core', '0013_alter_playableclass_icon_alter_spec_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gendername',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gender'),
        ),
        migrations.AlterField(
            model_name='gendername',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.locale'),
        ),
    ]
