# Generated by Django 4.0.2 on 2022-04-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_gendername_gender_alter_gendername_locale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='allowed_classes',
        ),
    ]
