# Generated by Django 4.0.2 on 2022-04-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_race_allowed_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realmname',
            name='last_updated',
        ),
    ]
