# Generated by Django 4.0.2 on 2022-04-22 15:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_realmname_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playableclass',
            name='icon',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/icons/class', location='None/icons/class/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='spec',
            name='icon',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/icons/spec', location='None/icons/specs/'), upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('name', 'realm')},
        ),
    ]
